### ISSUE TITLE
Branch: Direwolf

### ISSUE THREAD

**Issue by Katelyn-SN** [thomas15v/TurtleFix#2]
Turtles do not function in claimed or unclaimed land they break blocks either way. But only will do around 2 blocks at max before returning to surface
![2014-09-21_01 46 05](https://cloud.githubusercontent.com/assets/2229748/4347876/a267788c-416f-11e4-8256-0d13c3764f50.png)

**Comment by Katelyn-SN** [comment]
Also from discussion from irc you didn't post the event apparently as such event.canceled will never be false

**Comment by Katelyn-SN** [comment]
Due note fix only working with ForgePermitter instaled

**Comment by thomas15v** [comment]
Ya, this mod just passes the event. At this point its up to bukkit to cancel it or not.
