### ISSUE TITLE
[Request] 1.7.10 Support

### ISSUE THREAD

**Issue by cookta2012** [thomas15v/TurtleFix#6]
Could we see a version for 1.7.10. I got it to compile for 1.7.10 by updating the events but I cannot get the bytecode injection.

**Comment by thomas15v** [comment]
Hmmm, Sorry that I saw this late. To give you a clue, you need to decompile computercraft to see how it works internaly. And than inject in to it. I will look to give an update after my exams :octocat:. Thats after febuari, but nothing stops you from figuring this out by yourself ;).

You can get some extra information here: https://github.com/MazeXD/PatchEngine/tree/old-1.4.7 . This project depends highly on patchengine. And I also learned most of the bytecode stuff their.

**Comment by Katelyn-SN** [comment]
Don't waste your time @thomas15v I already got it finished ill push the commit when i get home from vacation on the 1st. I already corrected the ComputerCraft, and Thaumcraft patches.

**Comment by thomas15v** [comment]
@tf101-wizard oke :+1:.

**Comment by Katelyn-SN** [comment]
Sorry about that @thomas15v got held up with some server bugs that needed my attention and when i went back to upload it to github my install for git was broken so ill have to take a look at that tomorrow. Just a little notice there has been many versions of thaumcraft and only a few are supported by my changes.

**Comment by cookta2012** [comment]
What happened to 1.7.10 support?

**Comment by Katelyn-SN** [comment]
Delays more delays and forgetfulness its sitting right here I just keep forgetting to update it

**Comment by thomas15v** [comment]
Atm I have to many problems with 1.4.7 dupes. This will have to wait, I am sorry :/.

**Comment by cookta2012** [comment]
waht? 1.4.7 ??? @thomas15v

@tf101-wizard I understand life :p

**Comment by thomas15v** [comment]
I own/help 1.4.7 tekkit lite servers. Tekkit Lite is like a dupe (item duplication) pack. Its a constant flow of bugs/dupes that have to be fixed ;-;. Also I have the same issue @tf101-wizard has. School is consuming me ;-;. So I hardly have time for projects like these.

**Comment by Katelyn-SN** [comment]
Keep in mind I've yet to test my own changes on computercraft versions past 1.65 being that there were a ton of changes between my tested version and the 1.7X builds I'm not sure if it will even work.

**Comment by cookta2012** [comment]
just curious any progress?
