### ISSUE TITLE
Request 1.4.7 support

### ISSUE THREAD

**Issue by Mitelin** [thomas15v/TurtleFix#8]
Hello how hard whit it be make this work for 1.4.7 
1.2.5 have good protection
1.4.7 second most played version have nothing

Whud you be so kind to port it for 1.4.7 ?

**Comment by thomas15v** [comment]
https://github.com/TheFantasyCraft/Patches.
Already been their :+1:. If you have any other request or problems with it you could also contact me on skype (just send a mail and I send it to you).
